/*
 * 004_Spi.c
 *
 *  Created on: Jan 15, 2026
 *      Author: smlby
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <gpio.h>
#include <gpio_cfg.h>
#include <gpio_reg.h>
#include <rcc.h>
#include <stdint.h>
#include "icu.h"
#include "exti.h"
#include "exti_cfg.h"
#include "nvic.h"
#include "spi.h"
#include "spi_cfg.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delayFunc (void);
void delayFunc (void)
{
	for(uint32_t i = 0 ; i<5; i++);
}


#define IRQ_GPIO_PA0	0u

int main(void)
{

	uint8_t retval = 0xFF;

	uint8_t channel1[1] = {11};
	uint8_t channel2[1] = {121};
	uint8_t channel3[1] = {122};
	uint8_t channel4[1] = {231};
	uint8_t channel5[1] = {241};

	GPIOA_PCLK_EN();
	GPIOB_PCLK_EN();
	GPIOD_PCLK_EN();
	SPI1_PCLK_EN();
	SPI2_PCLK_EN();
	GPIO_Init(&Gpio_ConfigHandle);
	Nvic_EnableIRQ(35);
	Nvic_EnableIRQ(36);
	//EXTI_Init(&EXTI_InitHandle);
	//ICU_EnableNotification(IRQ_GPIO_PA0);

	Spi_Init(&SpiConfig);

	while(1)
	{

		retval = Spi_WriteIB(SPI_CHANNEL_1,channel1);
		retval = Spi_WriteIB(SPI_CHANNEL_2,channel2);
		retval = Spi_WriteIB(SPI_CHANNEL_3,channel3);
		retval = Spi_WriteIB(SPI_CHANNEL_4,channel4);
		retval = Spi_WriteIB(SPI_CHANNEL_5,channel5);

		retval = Spi_SyncTransmit(SPI_SEQUENCE_1);
		retval = Spi_AsyncTransmit(SPI_SEQUENCE_2);
		retval = Spi_AsyncTransmit(SPI_SEQUENCE_3);
		delayFunc();
		Spi_Main();

	}

    /* Loop forever */
	for(;;);
}
