/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <gpio.h>
#include <gpio_cfg.h>
#include <gpio_reg.h>
#include <rcc.h>
#include <stdint.h>
#include "icu.h"
#include "exti.h"
#include "exti_cfg.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delayFunc (void);
void delayFunc (void)
{
	for(uint32_t i = 0 ; i<500; i++);
}

#define PPB_BASEADDR			0xE0000000 /*!< Private Peripheral Bus (PPB) */

#define NVIC_BASEADDR			(PPB_BASEADDR + 0xE100)

#define NVIC_ISR				(volatile uint32_t*)(NVIC_BASEADDR + 0x0000u)

#define IRQ_GPIO_PA0	0u

int main(void)
{



	GPIOA_PCLK_EN();
	GPIOD_PCLK_EN();
	GPIO_Init(&Gpio_ConfigHandle);
	EXTI_Init(&EXTI_InitHandle);
	ICU_EnableNotification(IRQ_GPIO_PA0);

	*NVIC_ISR |= (1 << 6);
	while(1)
	{
		if (0 != ICU_Ch0_notification)
		{
			GPIO_ToggleOutputPin(GPIO_CHANNEL_PD12);
			GPIO_ToggleOutputPin(GPIO_CHANNEL_PD13);
			GPIO_ToggleOutputPin(GPIO_CHANNEL_PD14);
			GPIO_ToggleOutputPin(GPIO_CHANNEL_PD15);

			delayFunc();

			ICU_Ch0_notification = 0;
		}

		delayFunc();
	}

    /* Loop forever */
	for(;;);
}
